# Site settings
title: "Cerb"
company: "Webgroup Media, LLC."
copyright: 2002-2016
email: support@webgroupmedia.com
description: >
  Cerb is a fast, flexible toolkit for web-based collaboration and workflow automation. It has continuously evolved for more than 14 years based on the feedback of thousands of organizations.
url: "http://cerb.io"
baseurl: ""
logo: assets/cerb_logo.png
facebook_username: cerbapp
twitter_username: cerb_app
github_username:  wgm
timezone: America/Los_Angeles
encoding: utf-8

# Blog
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: ""

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/
  integrations:
    output: true
    permalink: /integrations/:path/

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: false
gems:
#  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-gist

# Pagination
#paginate: 10
#paginate_path: "/blog/page:num/"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
      jumbotron:
        title: Documentation
  -
    scope:
      path: ""
      type: "integrations"
    values:
      layout: "integration"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      jumbotron:
        title: Blog
        tagline: Stay up to date on the latest project news
  -
    scope:
      path: "recipes/aws-lambda"
    values:
      layout: "integration"
      jumbotron:
        title: Cerb + AWS Lambda
        tagline: Integrate with Lambda functions in Amazon Web Services
  -
    scope:
      path: "recipes/recaptcha"
    values:
      layout: "integration"
      jumbotron:
        title: Cerb + reCAPTCHA
        tagline: Integrate with reCAPTCHA to combat abuse and spam in forms
  -
    scope:
      path: "recipes/slack"
    values:
      layout: "integration"
      jumbotron:
        title: Cerb + Slack
        tagline: Integrate with Slack messaging for teams
  -
    scope:
      path: "recipes/webhooks"
    values:
      layout: "integration"
      jumbotron:
        title: Cerb + Webhooks
        tagline: Integrate with arbitrary webhook notifications
