# Site settings
title: "Cerb"
company: "Webgroup Media, LLC."
copyright: 2002-2017
email: support@webgroupmedia.com
description: >
  Cerb enhances the productivity of online teams with web-based collaboration and automation tools.
url: "http://cerb.ai"
baseurl: ""
logo: assets/cerb_logo.png
facebook_username: cerb.app
twitter_username: cerb_ai
github_username:  wgm
timezone: America/Los_Angeles
encoding: utf-8

# Blog
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: ""

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/
  integrations:
    output: true
    permalink: /guides/:path/

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: false
gems:
#  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-gist

# Pagination
#paginate: 10
#paginate_path: "/blog/page:num/"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
      jumbotron:
        title: Documentation
  -
    scope:
      path: ""
      type: "integrations"
    values:
      layout: "integration"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      jumbotron:
        title: Blog
        tagline: Stay up to date on the latest project news