# Site settings
title: "Cerb"
company: "Webgroup Media, LLC."
copyright: 2002-2017
email: support@webgroupmedia.com
description: >
  Cerb boosts team productivity with bot-powered email and workflow automation. Create bot helpers from your browser without coding. Start a free evaluation with no time limit or feature restrictions.
url: "https://cerb.ai"
baseurl: ""
logo: assets/cerb_logo.png
facebook_username: cerb.app
twitter_username: cerb_ai
github_username:  wgm
timezone: America/Los_Angeles
encoding: utf-8

# Blog
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: ""

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/
  guides:
    output: true
    permalink: /guides/:path/
  packages:
    output: true
    permalink: /packages/:path/
  plugins:
    output: true
    permalink: /plugins/:path/

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  parse_block_html: false
plugins:
  - jekyll-redirect-from

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
      jumbotron:
        title: Documentation
  -
    scope:
      path: ""
      type: "guides"
    values:
      layout: "integration"
  -
    scope:
      path: ""
      type: "packages"
    values:
      layout: "integration"
  -
    scope:
      path: ""
      type: "plugins"
    values:
      layout: "integration"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      jumbotron:
        title: Blog
        tagline: Release announcements, helpful tips, and community discussion
